spring.application.name=EsameEcommerce

# chiavi per configurare il driver per Postgres
spring.datasource.url=jdbc:postgresql://localhost:5432/ecommerce
NotExist=true&autoReconnect=true&allowPublicKeyRetrieval=true&useSSL=false
spring.datasource.username=postgres
spring.datasource.password=postgres

#chiavi per jpa : attivano il tool di autogenerazione delle tabelle
spring.jpa.hibernate.ddl-auto=update

#mostra sul server le istruzioni sql eseguite da Hibernate
spring.jpa.show-sql=true